require("core.packer")
require("core.init")
require("core.set")
require("core.remap")
require("config.theme")
require("config.keybindings")
require("config.treesitter")
require("config.fugitive")
require("config.barbar")
require("config.lsp")
require("config.terminal")
-- require("config.toggleterm")
require("config.neotree")
require("config.lualine")
require("config.whichkey")
